---
title: "Genes in AC toxicity-associated loci response to CX5461 and DOX"
author: "Sayan Paul"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
---

### **📌 Load Required Libraries**
```{r setup, echo=TRUE, message=FALSE}
# Load required libraries
library(tidyverse)
library(gridtext)
library(scales)
library(kableExtra)
library(qvalue)
library(data.table)
library(ComplexHeatmap)
library(readr)
library(limma)
library(edgeR)
library(ComplexHeatmap)
library(circlize)
library(grid)
library(tidyr)
library(reshape2)
library(dplyr)
library(org.Hs.eg.db)
```

## **📌 Read and Process DEG Data**
```{r load_DEGs, echo=TRUE, results='hide', message=FALSE, warning=FALSE}
# Load DEGs Data
CX_0.1_3 <- read.csv("data/DEGs/Toptable_CX_0.1_3.csv")
CX_0.1_24 <- read.csv("data/DEGs/Toptable_CX_0.1_24.csv")
CX_0.1_48 <- read.csv("data/DEGs/Toptable_CX_0.1_48.csv")
CX_0.5_3 <- read.csv("data/DEGs/Toptable_CX_0.5_3.csv")
CX_0.5_24 <- read.csv("data/DEGs/Toptable_CX_0.5_24.csv")
CX_0.5_48 <- read.csv("data/DEGs/Toptable_CX_0.5_48.csv")

DOX_0.1_3 <- read.csv("data/DEGs/Toptable_DOX_0.1_3.csv")
DOX_0.1_24 <- read.csv("data/DEGs/Toptable_DOX_0.1_24.csv")
DOX_0.1_48 <- read.csv("data/DEGs/Toptable_DOX_0.1_48.csv")
DOX_0.5_3 <- read.csv("data/DEGs/Toptable_DOX_0.5_3.csv")
DOX_0.5_24 <- read.csv("data/DEGs/Toptable_DOX_0.5_24.csv")
DOX_0.5_48 <- read.csv("data/DEGs/Toptable_DOX_0.5_48.csv")

Entrez_IDs <- c(57161,3958,80059,5095,10499,4692,108,7991,57110,6272,29899,23155,8803,80856,23327,54477,23151,55020,150383,9620,78996,11128,4023,8214,79730,323,344595,5066,23262,54826,5916,23371,283337,64078,80010,1933,10818,51020)

# Subset the toptable based on the entrez IDs and select specific columns

subset_toptable1 <- CX_0.1_3[CX_0.1_3$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]


subset_toptable2 <- CX_0.1_24[CX_0.1_24$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]


subset_toptable3 <- CX_0.1_48[CX_0.1_48$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]


subset_toptable3 <- CX_0.1_48[CX_0.1_48$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable4 <- CX_0.5_3[CX_0.5_3$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable5 <- CX_0.5_24[CX_0.5_24$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable6 <- CX_0.5_48[CX_0.5_48$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable7 <- DOX_0.1_3[DOX_0.1_3$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable8 <- DOX_0.1_24[DOX_0.1_24$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable9 <- DOX_0.1_48[DOX_0.1_48$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable10 <- DOX_0.5_3[DOX_0.5_3$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable11 <- DOX_0.5_24[DOX_0.5_24$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]

subset_toptable12 <- DOX_0.5_48[DOX_0.5_48$Entrez_ID %in% Entrez_IDs, c("Entrez_ID", "logFC", "adj.P.Val")]
```

## **📌 Add metadata and combine all subsets**
```{r Read mapping counts, echo=FALSE, results='hide', include=FALSE}
# Function to add columns and combine data
add_metadata <- function(data, drug, conc, time) {
  data %>%
    mutate(Drug = drug, Conc = conc, Time = time)
}

# Add metadata and combine all subsets
combined_data <- bind_rows(
  add_metadata(subset_toptable1, "CX", 0.1, 3),
  add_metadata(subset_toptable2, "CX", 0.1, 24),
  add_metadata(subset_toptable3, "CX", 0.1, 48),
  add_metadata(subset_toptable4, "CX", 0.5, 3),
  add_metadata(subset_toptable5, "CX", 0.5, 24),
  add_metadata(subset_toptable6, "CX", 0.5, 48),
  add_metadata(subset_toptable7, "DOX", 0.1, 3),
  add_metadata(subset_toptable8, "DOX", 0.1, 24),
  add_metadata(subset_toptable9, "DOX", 0.1, 48),
  add_metadata(subset_toptable10, "DOX", 0.5, 3),
  add_metadata(subset_toptable11, "DOX", 0.5, 24),
  add_metadata(subset_toptable12, "DOX", 0.5, 48)
)

# Convert Entrez IDs to Gene symbols
combined_data <- combined_data %>%
  mutate(Gene = mapIds(
    org.Hs.eg.db,
    keys = as.character(Entrez_ID),
    column = "SYMBOL",
    keytype = "ENTREZID",
    multiVals = "first"
  ))

# Reorder columns
final_data <- dplyr::select(combined_data, Entrez_ID, Gene, logFC, adj.P.Val, Drug, Conc, Time)
```


## **📌Create a matrix and heatmap**
```{r Data_prep, echo=TRUE, message=FALSE, fig.height=10, fig.width=10}
# Assuming your dataframe is named data
# Add a column for significance stars
final_data <- final_data %>%
  mutate(Significance = ifelse(adj.P.Val < 0.05, "*", ""))

# Create a matrix for the heatmap (logFC values)
logFC_matrix <- acast(final_data, Gene ~ paste(Drug, Conc, Time, sep = "_"), value.var = "logFC")

# Create a matrix for the significance annotations
signif_matrix <- acast(final_data, Gene ~ paste(Drug, Conc, Time, sep = "_"), value.var = "Significance")

# Split column names into Drug, Conc, and Time
colnames_split <- strsplit(colnames(logFC_matrix), "_")
drug <- sapply(colnames_split, function(x) x[1])
conc <- sapply(colnames_split, function(x) x[2])
time <- sapply(colnames_split, function(x) x[3])

# Create the desired column order: CX 0.1 3hr, CX 0.5 3hr, CX 0.1 24hr, CX 0.5 24hr, CX 0.1 48h, CX 0.5 48h,
# DOX 0.1 3hr, DOX 0.5 3hr, DOX 0.1 24hr, DOX 0.5 24hr, DOX 0.1 48h, DOX 0.5 48h
desired_order <- c("CX_0.1_3", "CX_0.5_3", "CX_0.1_24", "CX_0.5_24", "CX_0.1_48", "CX_0.5_48",
                   "DOX_0.1_3", "DOX_0.5_3", "DOX_0.1_24", "DOX_0.5_24", "DOX_0.1_48", "DOX_0.5_48")

# Reorder columns in the matrix based on the desired order
column_names <- paste(drug, conc, time, sep = "_")
column_order <- match(desired_order, column_names)
logFC_matrix <- logFC_matrix[, column_order]
signif_matrix <- signif_matrix[, column_order]
drug <- drug[column_order]
conc <- conc[column_order]
time <- time[column_order]

# Prepare annotations matching the column structure
ha_top <- HeatmapAnnotation(
  Drug = drug,
  Conc = conc,
  Time = time,
  col = list(Drug = c("CX" = "blue", "DOX" = "red"),
             Conc = c("0.1" = "lightgreen", "0.5" = "darkgreen"),
             Time = c("3" = "yellow", "24" = "orange", "48" = "purple")),
  annotation_height = unit(c(2, 2, 2), "cm")
)

# Create the heatmap
heatmap <- Heatmap(logFC_matrix, name = "logFC", top_annotation = ha_top,
                   cell_fun = function(j, i, x, y, width, height, fill) {
                     grid.text(signif_matrix[i, j], x, y, gp = gpar(fontsize = 10))
                   },
                   show_row_names = TRUE, show_column_names = FALSE,
                   column_title = "Genes in AC toxicity-associated loci response to CX5461 and DOX",
                   column_title_gp = gpar(fontsize = 16, fontface = "bold"),
                   cluster_columns = FALSE)  # Disable column clustering

# Draw the heatmap
draw(heatmap, heatmap_legend_side = "right", annotation_legend_side = "right")
```



